# Generated by Django 3.2.9 on 2022-01-06 15:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200, verbose_name='food_name')),
                ('food_image', models.ImageField(upload_to='media/')),
                ('food_description', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='food_description')),
                ('food_created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_category_name', models.CharField(max_length=200, verbose_name='food_category_name')),
            ],
        ),
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_category_name', models.CharField(max_length=200, verbose_name='meal_category_name')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(20000)])),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_status', models.CharField(choices=[('ordered', 'ordered'), ('order_confirmed', 'order_confirmed'), ('is_sending', 'is_sending'), ('delivered', 'delivered')], default='-----', max_length=16)),
                ('delivery_time', models.TimeField(auto_now_add=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('total_price', models.IntegerField(null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.address')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200, verbose_name='restaurant_name')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_branch_name', models.CharField(max_length=200, verbose_name='restaurant_branch_name')),
                ('restaurant_branch_description', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='restaurant_branch_description')),
                ('restaurant_branch_created_date', models.DateField(auto_now_add=True)),
                ('restaurant_branch_status', models.BooleanField(default=True, verbose_name='active')),
                ('is_main_branch', models.BooleanField(default=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantbranchs', to='accounts.address')),
                ('food_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='orderonline.foodcategory')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branchs', to='accounts.restaurantmanager')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_branchs', to='orderonline.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitems', to='orderonline.menu')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='orderonline.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='orderonline.restaurantbranch'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_order', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_item',
            field=models.ManyToManyField(related_name='order', to='orderonline.Menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_menus', to='orderonline.restaurantbranch'),
        ),
        migrations.AddField(
            model_name='menu',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_menu', to='orderonline.food'),
        ),
        migrations.AddField(
            model_name='food',
            name='food_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menues', to='orderonline.foodcategory'),
        ),
        migrations.AddField(
            model_name='food',
            name='meal',
            field=models.ManyToManyField(related_name='meal_menues', to='orderonline.MealCategory'),
        ),
    ]
