# Generated by Django 3.2.9 on 2021-12-27 12:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200, verbose_name='food_name')),
                ('food_image', models.ImageField(upload_to='media/')),
                ('food_description', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='food_description')),
                ('food_created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_category_name', models.CharField(max_length=200, verbose_name='food_category_name')),
            ],
        ),
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_category_name', models.CharField(max_length=200, verbose_name='meal_category_name')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200, verbose_name='restaurant_name')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('number', models.IntegerField()),
                ('food', models.ManyToManyField(related_name='food_menu', to='orderonline.Food')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='food_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menues', to='orderonline.foodcategory'),
        ),
        migrations.AddField(
            model_name='food',
            name='meal',
            field=models.ManyToManyField(related_name='meal_menues', to='orderonline.MealCategory'),
        ),
        migrations.CreateModel(
            name='RestaurantBranch',
            fields=[
                ('restaurant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orderonline.restaurant')),
                ('restaurant_branch_name', models.CharField(max_length=200, verbose_name='restaurant_branch_name')),
                ('restaurant_branch_description', models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='restaurant_branch_description')),
                ('restaurant_branch_created_date', models.DateField(auto_now_add=True)),
                ('restaurant_branch_status', models.BooleanField(default=True, verbose_name='active')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantbranchs', to='accounts.address')),
                ('food_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='orderonline.foodcategory')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branchs', to='accounts.restaurantmanager')),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branch_menus', to='orderonline.menu')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_branchs', to='orderonline.restaurant')),
            ],
            bases=('orderonline.restaurant',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_status', models.CharField(choices=[('ordered', 'ordered'), ('order_confirmed', 'order_confirmed'), ('is_sending', 'is_sending'), ('delivered', 'delivered')], default='-----', max_length=16)),
                ('order_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('delivery_time', models.TimeField(auto_now_add=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='accounts.customer')),
                ('customer_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.address')),
                ('food', models.ManyToManyField(related_name='order', to='orderonline.Food')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orderonline.restaurantbranch')),
            ],
        ),
    ]
